import time
import uuid
import json
from typing import Dict, Any, List
from services.kb_service import (
    GithubFinding, GithubReviewDecision, GithubReviewerNote,
    GithubTask, GithubFalsePositive, GithubSLATracking, GithubAuditLog
)

class GithubGovernanceEngine:
    """
    Core engine handling Human-in-the-Loop (HITL) review queue, SLA tracking,
    and automatic task dispatching for the GitHub Intelligence module.
    """
    def __init__(self, kb_session):
        self.session = kb_session

    def create_findings_from_scan(self, repo_id: str, repo_name: str, branch: str, ai_findings: List[Dict[str, Any]]):
        """Converts raw AI insights into structured governance findings."""
        for finding in ai_findings:
            finding_id = f"GH-FND-{uuid.uuid4().hex[:8].upper()}"
            
            # Map dynamic AI severity to SLA deadline
            sla_hours = {"Critical": 4, "High": 24, "Medium": 72, "Low": 168}.get(finding.get('severity', 'Medium'), 72)
            deadline = time.time() + (sla_hours * 3600)

            db_finding = GithubFinding(
                id=finding_id,
                repository_id=repo_id,
                branch=branch,
                title=finding.get('title', 'AI Detected Anomaly'),
                finding_type=finding.get('type', 'Architecture Issue'),
                severity=finding.get('severity', 'Medium'),
                confidence_score=finding.get('confidence', 0.85),
                business_impact=finding.get('impact', 'Potential technical debt accumulation.'),
                architecture_impact=finding.get('architecture_impact', 'Minor structural coupling.'),
                affected_files=json.dumps(finding.get('files', [])),
                affected_modules=json.dumps(finding.get('modules', [])),
                evidence=finding.get('evidence', 'Detected via AI source parsing.'),
                ai_reasoning=finding.get('reasoning', 'Pattern matching suggests anti-pattern.'),
                remediation=finding.get('remediation', 'Refactor according to standard practices.'),
                status="PENDING_REVIEW",
                assigned_team=self._auto_assign_team(finding.get('type', '')),
                created_at=time.time()
            )
            self.session.add(db_finding)
            
            # SLA Tracking
            self.session.add(GithubSLATracking(
                id=uuid.uuid4().hex, finding_id=finding_id, severity=finding.get('severity', 'Medium'), deadline=deadline
            ))
            
            # Audit Trail
            self._log_audit(finding_id, "SYSTEM", "Finding generated by AI", f"Severity: {finding.get('severity')}")

        try:
            self.session.commit()
        except Exception as e:
            self.session.rollback()

    def _auto_assign_team(self, finding_type: str) -> str:
        t = finding_type.lower()
        if 'ci' in t or 'cd' in t or 'pipeline' in t: return "DevOps Team"
        if 'auth' in t or 'security' in t: return "Security Team"
        if 'frontend' in t or 'ui' in t: return "Frontend Team"
        if 'architecture' in t or 'db' in t: return "Backend Team"
        return "Platform Team"

    def get_review_queue(self, repo_id: str = None) -> List[Dict]:
        query = self.session.query(GithubFinding).filter(GithubFinding.status == "PENDING_REVIEW")
        if repo_id:
            query = query.filter(GithubFinding.repository_id == repo_id)
        
        findings = query.all()
        return [self._row_to_dict(f) for f in findings]

    def get_tasks(self) -> List[Dict]:
        tasks = self.session.query(GithubTask).all()
        return [self._row_to_dict(t) for t in tasks]

    def _row_to_dict(self, row) -> dict:
        return {c.name: getattr(row, c.name) for c in row.__table__.columns}

    def _log_audit(self, finding_id: str, actor: str, action: str, details: str):
        self.session.add(GithubAuditLog(
            id=uuid.uuid4().hex, finding_id=finding_id, action=action, actor=actor, details=details, timestamp=time.time()
        ))

    def submit_decision(self, finding_id: str, reviewer: str, decision: str, notes: str = ""):
        finding = self.session.query(GithubFinding).filter(GithubFinding.id == finding_id).first()
        if not finding: return {"error": "Finding not found"}

        decision = decision.upper()
        finding.status = "APPROVED" if decision == "APPROVE" else "REJECTED" if decision == "REJECT" else "ESCALATED"
        finding.reviewer = reviewer

        # Log decision
        self.session.add(GithubReviewDecision(
            id=uuid.uuid4().hex, finding_id=finding_id, decision=decision, reviewer=reviewer, notes=notes, timestamp=time.time()
        ))
        
        if notes:
            self.session.add(GithubReviewerNote(
                id=uuid.uuid4().hex, finding_id=finding_id, reviewer=reviewer, note=notes, timestamp=time.time()
            ))

        self._log_audit(finding_id, reviewer, f"Review Decision: {decision}", notes)

        # Workflows
        if decision == "APPROVE":
            # Dispatch Task
            self.session.add(GithubTask(
                id=f"TASK-{uuid.uuid4().hex[:8]}", finding_id=finding_id, assigned_team=finding.assigned_team, 
                eta=time.time() + (3*86400), status="OPEN", created_at=time.time()
            ))
            finding.status = "ASSIGNED"
        
        elif decision == "REJECT":
            # Add to false positive memory to suppress future occurrences
            self.session.add(GithubFalsePositive(
                id=uuid.uuid4().hex, repository_id=finding.repository_id, finding_type=finding.finding_type,
                rejection_reason=notes, architecture_preference="Derived from rejection", created_at=time.time()
            ))
            
        try:
            self.session.commit()
            return {"success": True, "status": finding.status}
        except Exception as e:
            self.session.rollback()
            return {"error": str(e)}

