# -*- coding: utf-8 -*-
"""GitHub PR comments: post formatted analysis results on pull requests (requires GITHUB_TOKEN)."""

import os
from typing import Dict
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
import httpx

from utils.git_ops import parse_github_url

router = APIRouter()

GITHUB_API = "https://api.github.com"


class PRCommentRequest(BaseModel):
    repo_url: str = Field(..., description="GitHub repository URL (e.g. https://github.com/owner/repo)")
    pr_number: int = Field(..., description="Pull request number")
    analysis_results: Dict = Field(..., description="Analysis results to format and post")
    comment_type: str = Field(default="full", description="full, summary, or security_only")


def format_analysis_comment(results: Dict, comment_type: str) -> str:
    """Format analysis results as a markdown GitHub PR comment."""
    lines = []
    lines.append("## Autopsy AI - Automated Analysis Report")
    lines.append("")

    overall = results.get("overallScore", results.get("score", "N/A"))
    grade = results.get("grade", "")
    lines.append(f"**Overall Score: {overall}/100** {f'(Grade {grade})' if grade else ''}")
    lines.append("")

    if results.get("summary"):
        lines.append(f"> {results['summary']}")
        lines.append("")

    scores = results.get("scores", {})
    if scores:
        lines.append("### Score Breakdown")
        lines.append("| Category | Score |")
        lines.append("|----------|-------|")
        for key, val in scores.items():
            label = key.replace("_", " ").title()
            emoji = "green_circle" if val >= 80 else "yellow_circle" if val >= 60 else "red_circle"
            lines.append(f"| {label} | :{emoji}: {val}/100 |")
        lines.append("")

    if comment_type in ("full", "security_only"):
        issues = results.get("issues", results.get("vulnerabilities", []))
        if issues:
            lines.append("### Issues Found")
            lines.append("")
            for issue in issues[:15]:
                sev = issue.get("severity", "info")
                emoji = {"critical": "red_circle", "high": "orange_circle", "medium": "yellow_circle"}.get(sev, "white_circle")
                desc = issue.get("description", issue.get("what", ""))
                file_path = issue.get("file", issue.get("function_name", ""))
                lines.append(f"- :{emoji}: **{sev.upper()}** {desc}")
                if file_path:
                    lines.append(f"  - File: `{file_path}`")
                fix = issue.get("suggestion", issue.get("fix", issue.get("remediation", "")))
                if fix:
                    lines.append(f"  - Fix: {fix}")
            lines.append("")

    recs = results.get("topRecommendations", results.get("recommendations", []))
    if recs and comment_type == "full":
        lines.append("### Recommendations")
        for r in recs[:5]:
            if isinstance(r, dict):
                lines.append(f"1. **{r.get('title', '')}** - {r.get('description', '')}")
            else:
                lines.append(f"1. {r}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [Autopsy AI](https://github.com) - AI-Powered Software Auditing*")

    return "\n".join(lines)


@router.post("/comment")
async def post_pr_comment(request: PRCommentRequest):
    """Post analysis results as a comment on a GitHub PR."""
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="GITHUB_TOKEN not configured. Add it to your .env file.")

    try:
        owner, repo = parse_github_url(request.repo_url)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    comment_body = format_analysis_comment(request.analysis_results, request.comment_type)

    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues/{request.pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(url, headers=headers, json={"body": comment_body})
            if resp.status_code == 201:
                data = resp.json()
                return {
                    "status": "posted",
                    "commentId": data.get("id"),
                    "commentUrl": data.get("html_url"),
                    "pr": f"{owner}/{repo}#{request.pr_number}",
                }
            else:
                raise HTTPException(status_code=resp.status_code, detail=f"GitHub API error: {resp.text}")
    except httpx.HTTPError as e:
        raise HTTPException(status_code=502, detail=f"Failed to reach GitHub API: {str(e)}")


@router.post("/format-preview")
async def preview_comment(request: PRCommentRequest):
    """Preview the formatted comment without posting."""
    comment_body = format_analysis_comment(request.analysis_results, request.comment_type)
    return {"markdown": comment_body, "characterCount": len(comment_body)}
